name: Fetch File From URL

on:
  schedule:
    - cron: '15 8 * * 1-5'  # Runs on weekdays at 0815 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download file from URL
      run: |
        mkdir -p data
        curl -L "https://nickg83.pythonanywhere.com/downloads/asx_yfinance_eod.csv" -o data/asx_yfinance_eod.csv

    - name: Commit and push file
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add data/asx_yfinance_eod.csv
        git commit -m "Auto-update file from URL" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
